### ISSUE TITLE
Add vertical/horizontal line to a px.line figure

### ISSUE THREAD

**Issue by tjm165** [mckinsey/vizro#100]
### What's the problem this feature will solve?

Enable developers to portray the significance behind a particular x (or y) value

### Describe the solution you'd like

A simple mechanism for a developer to add a vertical (or horizontal) line to a given `px.line` figure. Please see the green line in the screenshot as an example of the expected output. 

<img width="1638" alt="Screenshot 2023-10-07 at 12 17 11 AM" src="https://github.com/mckinsey/vizro/assets/32528539/24bb4706-82b1-4ee9-b971-f82b118d039c">

### Alternative Solutions

I attempted multiple different parameter configurations of the `fig.add_vline` function as indicated in the [plotly docs](https://plotly.com/python/horizontal-vertical-shapes/) 

```
    my_figure = px.line(
                    df_gapminder,
                    x="year",
                    y="gdpPercap",
                    color="data",
                    labels={"year": "Year", "data": "Data", "gdpPercap": "GDP per capita"},
                    color_discrete_map={"Country": "#afe7f9", "Continent": "#003875"},
                    markers=True,
                )
    
    my_figure.add_vline(1970)
    # my_figure.add_vline(x=1970)
    # my_figure.add_vline(x=1970, line_width=3)
    # my_figure.add_vline(x=1970, line_width=3, line_dash="dash")
    # my_figure.add_vline(x=1970, line_width=3, line_dash="dash", line_color="green")
```

### Additional context

As noted in [the docs](https://plotly.com/python/horizontal-vertical-shapes/), this appears to be a feature implemented by plotly. I'm curious if:

1. This works on other people's machines - in which case it is an issue with my local MacOS
2. OR If this feature is currently supported through another mechanism
3. OR Suggestions on where to to start in order to support this feature

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hello @tjm165,

thanks for raising the issue! 

What you describe above is already possible by leveraging our custom charts, see this example [here](https://vizro.readthedocs.io/en/latest/pages/user_guides/custom_charts/#enhanced-plotlyexpress-chart-with-reference-line). Given that you use a post update layout, the only step you are missing in the example above is to wrap your chart with our `@capture("graph")` decorator and then use that chart in your dashboard configurations.

My using the `@capture("graph")` decorator you can basically create any custom plotly chart that returns a `go.Figure` and use it inside the Vizro dashboards :)

## Example

```
import pandas as pd

import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro.models.types import capture


def aggregate_data():
    df_gapminder = px.data.gapminder()
    df_gapminder_agg = px.data.gapminder()
    df_gapminder_agg["lifeExp"] = df_gapminder_agg.groupby(by=["continent", "year"])["lifeExp"].transform("mean")
    df_gapminder_agg["gdpPercap"] = df_gapminder_agg.groupby(by=["continent", "year"])["gdpPercap"].transform("mean")
    df_gapminder_agg["pop"] = df_gapminder_agg.groupby(by=["continent", "year"])["pop"].transform("sum")
    df_gapminder["data"] = "Country"
    df_gapminder_agg["data"] = "Continent"
    df_gapminder = pd.concat([df_gapminder_agg, df_gapminder], ignore_index=True)
    return df_gapminder

df_gapminder = aggregate_data()


@capture("graph")  # Note change here
def my_figure(data_frame):
    fig = px.line(
        data_frame=data_frame,
        x="year",
        y="gdpPercap",
        color="data",
        labels={"year": "Year", "data": "Data", "gdpPercap": "GDP per capita"},
        color_discrete_map={"Country": "#afe7f9", "Continent": "#003875"},
        markers=True,
    )
    fig.add_vline(x=1970, line_color="green", line_dash="dash")
    return fig


page = vm.Page(
    title="Country Analysis",
    layout=vm.Layout(grid=[[0, 1]]),
    components=[
        vm.Graph(
            id="bar_country",
            figure=px.bar(
                df_gapminder,
                x="year",
                y="pop",
                color="data",
                barmode="group",
                labels={"year": "Year", "data": "Data", "pop": "Population"},
                color_discrete_map={"Country": "#afe7f9", "Continent": "#003875"},
            ),
        ),
        vm.Graph(id="line_country", figure=my_figure(data_frame=df_gapminder)),
    ],
    controls=[
        vm.Filter(column="country", selector=vm.Dropdown(value="India", multi=False, title="Select country")),
        vm.Filter(column="year", selector=vm.RangeSlider(title="Select timeframe")),
    ],
)

dashboard = vm.Dashboard(pages=[page])
Vizro().build(dashboard).run()
```

This should then give you this:
![Screenshot 2023-10-07 at 10 37 00](https://github.com/mckinsey/vizro/assets/90609403/81930de0-91aa-4c11-afa8-a657c484bae2)

Hope that helps! The above example works on my machine so if it does not work on yours, it might be a local issue as you suggested. But I hope it does 🤞 

Let me know if you have any other questions

**Comment by tjm165** [comment]
Hi @huong-li-nguyen that did the trick for me. I really appreciate your help and explanation!

Just as a side note for anyone who comes across this- the `@capture("graph")` decorator comes from import `from vizro.models.types import capture`
