### ISSUE TITLE
A date filter

### ISSUE THREAD

**Issue by roldengarm** [mckinsey/vizro#101]
### What's the problem this feature will solve?

I'd like to have a date filter, so I can filter to a certain date range.

### Describe the solution you'd like

 I'd expect a "Start date" and "End date" filter to show up.

### Alternative Solutions

In our case, we only need to filter per month, so I can create a dropdown to filter to a certain month. However that is not very flexible.

### Additional context

In our case we've got a MongoDB and I use pymongo to retrieve the data, which converts date values to date objects.

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by maxschulz-COL** [comment]
Dear @roldengarm, 

thank you very much for your feature request, this is much appreciated! The is a very valid request, and the team will consider implementing this! 

In the meantime, you have already suggested a very good workaround. Creating a categorical filter with a dropdown may get you what you would like, and it would have the additional benefit of targeting disconnected months.

Another alternative approach (given that you only require months) would be to use the `RangeSlider` (which works on numerical columns) and eventually format the values displayed as dates.

Let us know what you think and how it goes - and thanks a again for contributing :)

**Comment by huong-li-nguyen** [comment]
The DatePicker was added in `vizro==0.1.14` 🥳 We encourage to upgrade to latest version.
