### ISSUE TITLE
Add support for openai >= 1.0.0

### ISSUE THREAD

**Issue by l0uden** [mckinsey/vizro#154]
### Description

vizro_ai is not working with openai package higher or equal to 1.0.0

https://github.com/mckinsey/vizro/actions/runs/6804870476/job/18503283998

### vizro version

0.1.6

### Python version

3.9

### OS

Linux

### How to Reproduce

1. Install openai >= 1.0.0
2. Run vizro_ai package

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by matheus695p** [comment]
Same here !

**Comment by maxschulz-COL** [comment]
Solved with https://github.com/mckinsey/vizro/pull/369
