### ISSUE TITLE
Sliders doesn't work with big numbers

### ISSUE THREAD

**Issue by l0uden** [mckinsey/vizro#160]
### Description

If you configure sliders with big numbers and change it using input field you'll get an error:
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside
componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent 
infinite loops.
```

<img width="305" alt="image" src="https://github.com/mckinsey/vizro/assets/35569332/a00f9606-8048-45a8-9285-16867c4374fe">

### vizro version

0.1.7

### Python version

3.9

### OS

Mac

### How to Reproduce

1. Use gapminder dataset
2. Configure range_slider like this: `RangeSlider(step=1000000.0, min=1000000, max=10000000)` for `pop` column
3. Try to change slider value inside using input form

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
@petar-qb are you ok to look at this one? 🙏

**Comment by petar-qb** [comment]
Solved with the following PR: https://github.com/mckinsey/vizro/pull/173
