### ISSUE TITLE
Non equal distribution of space when using cards

### ISSUE THREAD

**Issue by pieterseyns** [mckinsey/vizro#177]
### Question

When using a card and a graph on the same page, the space is distributed equally. What setting do you need to apply to make the card smaller.

### Code/Examples

components=[
            vm.Card(
            text="""
                ### Card Title
             text
            """ 
),
               
            vm.Graph(
                id="val_stocks",
                figure= code to get some figure
                ),
            ),

### vizro version

0.1.3

### OS

MacOs

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hello @pieterseyns, the best way to achieve this is through [customising the layout grid](https://vizro.readthedocs.io/en/stable/pages/user_guides/layouts/?h=layout#customizing-the-grid-arrangement). e.g. if you wanted to put a small card next to a graph, you could specify:
```
vm.Page(layout = [0, 1, 1, 1], components=[vm.Card(...), vm.Graph(...)])
```

This would create a grid that looks like this:
```
0 1 1 1
```

Where the card occupies the slot labelled with 0 and the graph occupies slots labelled with 1, and so the card would be 1/4 and the graph would be 3/4 of the page width.
