### ISSUE TITLE
ModuleNotFoundError: No module named 'vizro.tables'

### ISSUE THREAD

**Issue by bvbvtw** [mckinsey/vizro#179]
### Question

my version of Vizro: 0.1.0
Here is my code:
![image](https://github.com/mckinsey/vizro/assets/80054552/a12ffedc-ff82-42d6-92c0-4eecc9483269)
I'd like from vizro.tables import dash_data_table 
but the terminal will pop up the error: **ModuleNotFoundError: No module named 'vizro.tables'**

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @bvbvtw,

thanks a lot for using Vizro, much appreciated!

`vizro.tables` are introduced in the Vizro version: `0.1.6`. Just installing it (with `pip install vizro==0.1.6` from terminal) should solve the problem. More about Vizro releases you can find at https://github.com/mckinsey/vizro/releases.

Let us know if this did not work, and we can try further.
