### ISSUE TITLE
Editable data table

### ISSUE THREAD

**Issue by maajdl** [mckinsey/vizro#221]
### Question

Is there a vizro component that allows the edition of a data table?
Or would it be possible (easy) to create such a component?

### Other information

I would like to write a small app based on two small tables.
The user would need to fill in this table.

### vizro version

0.1.7

### Python version

3.11.5

### OS

macOS-14.2-arm64-arm-64bit

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hey @maajdl,

that's a very good question! 🧠 

Our existing [vm.Table](https://vizro.readthedocs.io/en/stable/pages/user_guides/table/#dash-datatable) model and `dash_data_table` function would enable you to do so. Under the hood, the `dash_data_table` function leverages the **Dash Data Table**, so you have access to all the underlying arguments. 

To configure an editable table, see this example from **Dash**: https://dash.plotly.com/datatable/editable

This would then look like this in **Vizro**:

```
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro.tables import dash_data_table

df = px.data.iris()

page = vm.Page(
    title="My editable Table",
    components=[
        vm.Table(
            id="my_chart",
            figure=dash_data_table(
                id="my_editable_table",
                data_frame=df,
                editable=True
            ),
        ),
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()
```

Let me know if this works for you and if you have any other questions 👍

**Comment by maajdl** [comment]
Thanks a lot, it works!
So looking into dash will help a lot!

**Comment by huong-li-nguyen** [comment]
That's great! 🚀 

Yes, for sure! A lot of things are possible if you consider that you can basically wrap any dash component inside Vizro :)
