### ISSUE TITLE
Add support for Latex in Markdown

### ISSUE THREAD

**Issue by Et9797** [mckinsey/vizro#233]
### What's the problem this feature will solve?

Use Latex in Markdown. dcc.Markdown supports MathJax: https://dash.plotly.com/dash-core-components/markdown#latex

### Describe the solution you'd like

Use Latex in Markdown of vm.Card to format my formulas

### Alternative Solutions

-

### Additional context

-

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hey @Et9797 ,

I've answered to your two questions [here](https://github.com/mckinsey/vizro/issues/234), as both questions follow the same solution approach :)

Best,
Li
