### ISSUE TITLE
How to add color to text in Markdown with vm.Card?

### ISSUE THREAD

**Issue by Et9797** [mckinsey/vizro#234]
### Question

I have some markdown text that I would like to have be colored red/green (percentual growth). How to accomplish this with vm.Card?

### Code/Examples

```markdown    
components=[
        vm.Card(
            text=f"""
                #### Dagelijkse virtuele bundel sales

                Gemiddelde groei in sales 2 maanden vóór en ná de kortingsverhoging:

                Absoluut (voor): 709 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Absoluut (na): 710

                Gecorrigeerd (voor): 709 &nbsp;&nbsp;&nbsp;&nbsp; Gecorrigeerd (na): 710 <p style="color: green">(+1.5%)</p>
            """
        ),
       ...
```

### Other information

For example, it's not possible right now to add HTML in the Markdown, eg: `<p style="color: green">(+1.5%)</p>`

### vizro version

0.1.7

### Python version

3.10

### OS

Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hello @Et9797 ,

Thanks for reaching out! 

I'll answer this question and your other [question](https://github.com/mckinsey/vizro/issues/233) here, as both will follow the same approach :) 

Even though all our components come with specific default settings, you are always able to leverage the full functionality of the underlying dash component by following the [guide on custom components](https://vizro.readthedocs.io/en/stable/pages/user_guides/custom_components/#extend-an-existing-component). You can either extend an existing component or create a new component (e.g. if the dash component is not added to our code basis yet). 

To do that, you can base your custom Card on our existing card and overwrite the properties you want to change, e.g., to turn on HTML evaluation and Latex evaluation, just set  `dangerously_allow_html=True` and `mathjax=True`.  This could then look like this:

### Example

```
from typing import Literal

import vizro.models as vm
from vizro import Vizro


class CustomCard(vm.Card):
    type: Literal["custom_card"] = "custom_card"

    # 1) Here, we override the build method of the underlying source component
    def build(self):
        card_build_obj = super().build()

        # 2) Overwrite the default settings as you like - card_build_obj[self.id] fetches the underlying dcc.Markdown
        card_build_obj[self.id].dangerously_allow_html = True
        card_build_obj[self.id].mathjax = True
        return card_build_obj


# 3) Enable your custom component as a Page component
vm.Page.add_type("components", CustomCard)

page = vm.Page(
    title="Custom Card",
    components=[
        CustomCard(
            text="""
            #### Dagelijkse virtuele bundel sales

            Gemiddelde groei in sales 2 maanden vóór en ná de kortingsverhoging:

            Absoluut (voor): 709 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Absoluut (na): 710

            Gecorrigeerd (voor): 709 &nbsp;&nbsp;&nbsp;&nbsp; Gecorrigeerd (na): 710  <p style="color:green;">(+1.5%)</p>

            <p style="color:green;">(+1.5%)</p>
            """
        ),
        CustomCard(
            text="""
            ## Introducing LaTeX using MathJax:

            This example uses the block delimiter:

            $$
            \\frac{1}{(\\sqrt{\\phi \\sqrt{5}}-\\phi) e^{\\frac25 \\pi}} =
            1+\\frac{e^{-2\\pi}} {1+\\frac{e^{-4\\pi}} {1+\\frac{e^{-6\\pi}}
            {1+\\frac{e^{-8\\pi}} {1+\\ldots} } } }
            $$

            This example uses the inline delimiter:

            $E^2=m^2c^4+p^2c^2$
            """
        ),
    ],
)


dashboard = vm.Dashboard(pages=[page])
Vizro().build(dashboard).run()
```
### (Optional) Add styling
To make it fit better into the overall styling, you might want to create a `.css` file and [add it to your assets folder](https://vizro--229.org.readthedocs.build/en/229/pages/user_guides/assets/). The code below ensures that your Latex code is appropriately styled:

```
span {
  color: var(--text-secondary);
}
```

### Result
![Screenshot 2023-12-21 at 10 15 39](https://github.com/mckinsey/vizro/assets/90609403/e6818d43-ac55-4ef7-a4fc-b4af55d4c158)

Note:  In the example above, the coloring still doesn't work where you've placed it. I've just tested it out in a pure Dash app, and it seems to be an issue with how Markdown renders the HTML code when you place the `<p style="color:green;">(+1.5%)</p>` directly after the text. I think the dcc.Markdown might be treating it differently, as the example line below works. For this case, I suggest reaching out to Dash directly.

I hope that helps, and let me know if you have any other questions! 👍 

Best,
Li
