### ISSUE TITLE
Getting FieldInfo error while running vizro  

### ISSUE THREAD

**Issue by rahulbhatia10** [mckinsey/vizro#246]
### Description

Installed vizro using the mentioned steps.
When ran a simple program of getting vizro version , it ended up in below error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

      7 from vizro_ai.chains import ModelConstructor
      8 from vizro_ai.chains._llm_models import LLM_MODELS
----> 9 from vizro_ai.components import (
     10     GetChartSelection,
     11     GetCodeExplanation,
     12     GetCustomChart,
     13     GetDataFrameCraft,
     14     GetDebugger,
     15     GetVisualCode,
     16 )
     17 from vizro_ai.utils import _safeguard_check
...
---> 35         if field and field.field_info.description:
     36             prop["description"] = field.field_info.description.split("\n")[0]
     37 else:

AttributeError: 'FieldInfo' object has no attribute 'field_info'

Please can you help here.

### Expected behavior

It should have outputted the version

### vizro version

0.1.0

### Python version

3.11.4

### OS

Windows

### How to Reproduce

Install package using pip install vizro_ai
Run the below program
from vizro_ai import VizroAI

print(VizroAI.__version__)

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by paritoshgupta23** [comment]
+1 to the above issue. 

I am on MacOS and tried using vizro-ai with virtual environments using 'venv' and 'conda' with python 3.8 to 3.11. 
Nothing seems to the work . 

Kindly look into the error.

Error: AttributeError: 'FieldInfo' object has no attribute 'field_info'

<img width="933" alt="Screenshot 2024-01-04 at 3 26 37 PM" src="https://github.com/mckinsey/vizro/assets/138758365/c68e3e6b-96d6-4902-9a77-2865c16f4b83">

Thanks!

**Comment by maxschulz-COL** [comment]
Hey guys,

thanks for posting the issue, I am looking into a fix right now and will update as soon as I have one.

**Comment by maxschulz-COL** [comment]
The issue should be ressolved with the release of `vizro-ai==0.1.1`: https://github.com/mckinsey/vizro/releases/tag/vizro-ai-0.1.1
