### ISSUE TITLE
Replace all `html.P()` with `html.Label()` in all form components

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#290]
### Question

Context why this is beneficial: https://teamtreehouse.com/community/labels-vs-paragraphs#:~:text=The%20tag%20is%20just,in%20the%20CSS.

### Code/Examples

Replace `html.P(self.title)` with `html.Label(self.title)` for all form components (dropdown, checklist, etc.) and where applicable

### Which package?

vizro

### Package version

0.1.9

### Python version

3.9

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
@AnnMarieW - is this something you are interested in completing? :) 
@antonymilne told me you suggested it and I think it's a good idea! Let me know if you are interested in taking this ticket yourself, otherwise would love to get your review on it 👍

**Comment by antonymilne** [comment]
FYI the advantage is more than just semantic here I think, e.g. you can activate a form field just by clicking the label instead https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label.

**Comment by AnnMarieW** [comment]
Sure I could do this one :slightly_smiling_face:
