### ISSUE TITLE
Documentation Enhancement

### ISSUE THREAD

**Issue by Rhanselman** [mckinsey/vizro#331]
### Which package?

vizro

### What's the problem this feature will solve?

It will save developers and analysts countless hours of implementing selectors. It will do this by giving a detailed gif or webp video of what each selector does with an example of that selector in use.
It does this by giving a visual representation reinforcing what it is that the selector does before implementation, guiding user in the correct application of a selector for their use case.

### Describe the solution you'd like

Under each selector in the documentation section. Have a use case gif/webp video of that selector for a use case.

### Alternative Solutions

Knowing what each selector already does through implementing. Trial and error.

### Additional context

This enhancement can save developers time in understanding what does what for their implementations.

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hi @Rhanselman and thank you for raising this issue. It's a great point and something we're already thinking of doing. In fact I hope we can go one step better and change our docs to use real live examples of the components running in a dashboard. This will mean that you can click on the selectors and interact with them, which would be even better than an animated gif/webp.

For the time being, the best ways to see real examples of all the components are:
* go to https://vizro.mckinsey.com/, which has some examples
* download our [`features` examples dashboard](https://github.com/mckinsey/vizro/tree/main/vizro-core/examples/features) and run `python app.py`. This should be a pretty complete view of all components we offer, though actually it seems to be missing some selectors like radio items and checklist right now. Eventually we hope this will also be hosted somewhere so it's easy to look at the examples without needing to download and run anything

FYI @maxschulz-COL @stichbury good to know what people are looking for with the docs. And @huong-li-nguyen should the features example dashboard have all the selectors on it?

**Comment by huong-li-nguyen** [comment]
Yes, we should definitely have it in! I also noticed that it was missing when I consolidated all the selectors. I have a dummy page already that we can add 👍

**Comment by antonymilne** [comment]
Nice, thank you! Probably worth doing a double check through all our public models just to make sure they're all in there somewhere.
