### ISSUE TITLE
How to export the dashboard so that can share to others?

### ISSUE THREAD

**Issue by TianzeWang** [mckinsey/vizro#350]
### Question

Same as the title, is there a way to export the dashboard so that can share to others? As you know sometimes my boss do not want to see the python file and run on his local environments... He just want a website-like stuff and view it directly.

### Which package?

None

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hey @TianzeWang,

to share a Vizro app, you need to deploy it to a server of your choice: https://vizro.readthedocs.io/en/stable/pages/user-guides/run/#deployment

Given that Vizro is built on top of Dash, similar guidance applies so this might be helpful: https://dash.plotly.com/deployment#heroku-for-sharing-public-dash-apps

The syntax may differ; e.g., `Vizro().build(dashboard) ` returns the app object if you are familiar with Dash already. So you might have to do something like this:

```
app = Vizro().build(dashboard)
server = app.dash.server
```

Hope that's helpful! 🤞

**Comment by antonymilne** [comment]
Just to add: the Dash docs are pretty outdated here. Heroku no longer has a free tier, so if you're looking for something that's free then [the route they recommend is render](https://community.plotly.com/t/heroku-replacement-for-deploying-dash-app-to-the-web-render/68918).

I've personally used render for vizro dashboards and it worked very smoothly. In due course we should update our docs to demonstrate this or have a project template that does it or have some kind of "one click deploy". FYI @maxschulz-COL.

**Comment by TianzeWang** [comment]
Thanks @huong-li-nguyen and @antonymilne for the kind explanation! Super helpful! Really appreciate it!
