### ISSUE TITLE
Decimal numbers are sometimes being cut-off in sliders/range-sliders

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#361]
### Description

Decimal numbers are sometimes being cut-off in sliders/range-sliders. 

![Screenshot 2024-03-12 at 10 00 53](https://github.com/mckinsey/vizro/assets/90609403/c2ddec5f-b46a-480f-a0a3-44c07b9f0d7d)

This seems to **only** happen when the `step` argument is not defined. When the `step` argument is defined the max-width of the input field seems to scale correctly:
 
<img width="306" alt="Screenshot 2024-03-12 at 14 52 27" src="https://github.com/mckinsey/vizro/assets/108531476/0b22f7de-49b4-470b-a44b-ba95c525d414">

However, it doesn't always happen, so it doesn't seem to be a pure CSS issue as e.g. these work:
![Screenshot 2024-03-12 at 10 02 11](https://github.com/mckinsey/vizro/assets/90609403/0339b8a5-0360-4402-9424-ecc1984fa749)

### Expected behavior

Input field expanding to its content and not cutting of digits after the separator.

### Which package?

vizro

### Package version

0.1.12

### Python version

3.9

### OS

-

### How to Reproduce

Run any example with sliders

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by nadijagraca** [comment]
This bug is raised in dash repo, issue [2791](https://github.com/plotly/dash/issues/2791)

Until the bug is fixed on Dash side, please always set `step` size for `Slider`/`RangeSlider` components.

**Comment by huong-li-nguyen** [comment]
@maxschulz-COL  - FYI for the bug you've mentioned in the last PR.
