### ISSUE TITLE
Restyle the documentation landing page

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#378]
This is a good issue for anyone with markdown experience who enjoys the styling/design aspect rather than writing copy. There's no knowledge of Vizro required.

The current landing page for documentation is rather bland https://vizro.readthedocs.io/en/stable/ and the presentation could potentially be improved.

It would be great to have some styling to improve it. We can start with the copy we have (although we do need to add a section to link to the demo example in the repo). Some basic redesign is all that is needed to boost the look and feel.

**Comment by sulphatet** [comment]
Hi, I would like to work on this, can this be assigned to me?

**Comment by stichbury** [comment]
Thank you for volunteering! We are making a few changes throughout our docs but one thing you could do, if you were interested in helping with changing the look of the docs, is to update the font across the docs to use [Inter](https://fonts.google.com/specimen/Inter). We only use Inter regular, medium and semi-bold.

If you wanted to look at the relevant CSS changes for Vizro and Vizro-AI docs to replace the existing font with that one, and if you felt confident about doing that, we are happy to accept a contribution of that change. Beyond that, for now, we are going to pause any changes subject to some guidance from our design team.

WDYT? Would you like to give it a try? Thanks @sulphatet!

**Comment by sulphatet** [comment]
Hi @stichbury 
Yes! I would love to work on that. 

From what I understand, I should be updating `vizro-core/docs/stylesheets/extra.css` and `vizro-ai/docs/stylesheets/extra.css`, is that right?

Thanks!

**Comment by stichbury** [comment]
I think it may be more straightforward than that, since we're using MkDocs Material theme. You can use https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/ for guidance.

**Comment by stichbury** [comment]
This is done and merged. Thanks @sulphatet ! 🌟 🏆
