### ISSUE TITLE
Add documentation about the demo example and clean up `examples`

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#379]
This is a good issue for someone interested in documentation. It doesn't require any particular knowledge of Vizro but does need an interest in poking through our [examples folder in within `vizro-core` for this repo](https://github.com/mckinsey/vizro/tree/main/vizro-core/examples) to see what is there and write about the layout and what the example shows. There's a[ basic style guide for docs creators here](https://vizro.readthedocs.io/en/stable/pages/development/documentation-style-guide/), but we are happy to take any contribution as we can run Vale over it to highlight any tweaks needed to follow the guidlines.

The `examples` folder in the repo holds the code for [the demo](https://vizro.mckinsey.com).

It isn't very well highlighted in the docs and we need to do this:

1. Add a section on the home page and a link to a page of text about the demo (mentioned in #378 which will restyle that whole page)
2. Add the page itself. That page should document the basics of the demo and how to work with it.
3. Add a section in the `examples` folder where any contributions of example code for #377 will be added.

**Comment by sneha9231** [comment]
can i get assigned with this issue?

**Comment by huong-li-nguyen** [comment]
@sneha9231 - I think this might be an outdated ticket as the demo is not the same anymore!

**Comment by antonymilne** [comment]
@stichbury Is this ticket still relevant?

**Comment by stichbury** [comment]
No, this ticket should now be closed since we've revised the demo to become the gallery - and have a separate set of (internal) tickets to make a few information architecture changes as a result. Apologies @sneha9231 that it's not one you could pick up, but thanks for the offer 🚀
