### ISSUE TITLE
typo in explore-components/#22-add-further-components

### ISSUE THREAD

**Issue by kaestro** [mckinsey/vizro#431]
### Question

![image](https://github.com/mckinsey/vizro/assets/32026095/72e86e98-5017-4a50-94fc-58d1e9ffe435)

I guess this needs to be fixed into 'create creative' or delete one create.

For the issue I was assigned was about checking link's adaptability, I wasn't sure if I were to change this and make an pull request.

### Which package?

None

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by stichbury** [comment]
Thanks for the spot. Wonder why Vale didn't find this...
