### ISSUE TITLE
Minor typo in "Explore Vizro" tutorial

### ISSUE THREAD

**Issue by yury-fedotov** [mckinsey/vizro#456]
### Description

[This line](https://github.com/mckinsey/vizro/blob/29590981afeab6b76783fc2f455323133d5ab2c0/vizro-core/docs/pages/tutorials/explore-components.md?plain=1#L45) contains a minor typo related to dictionary definition style. No space before `"Continent"` value.

And the fix is to just add a space to make it consistent with other sections of the docs.

```diff
- labels={"lifeExp": "Life Expectancy", "continent":"Continent"}),
+ labels={"lifeExp": "Life Expectancy", "continent": "Continent"}),
```

P.S. Sorry for reporting it this way and not via a PR, I don't have the dev setup with fork/DCO and all that stuff, but guess that existing maintainers can fix it in any next docs-related PR in a few seconds.

### Which package?

vizro

### Package version

0.1.16

### Python version

3.12

### OS

MacOS

### How to Reproduce

Just locate [this line](https://github.com/mckinsey/vizro/blob/29590981afeab6b76783fc2f455323133d5ab2c0/vizro-core/docs/pages/tutorials/explore-components.md?plain=1#L45).

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by stichbury** [comment]
Thanks @yury-fedotov I have added a fix (multiple lines had this issue) here: https://github.com/mckinsey/vizro/pull/464
