### ISSUE TITLE
New features available for dcc.Loading

### ISSUE THREAD

**Issue by AnnMarieW** [mckinsey/vizro#486]
### Which package?

vizro

### What's the problem this feature will solve?

Hi Vizro team :wave: 

I just wanted to let you know about some cool new features available for `dcc.Loading` in dash 2.17.0 

It's  now possible to:
 - Delay showing the spinner for a specified number of milliseconds - which eliminates the  flickering when the loading time is very short.  
 - Make the background visible and  customizable with CSS -- like adding `blur` or `opacity`.  This makes the transition between loading and ready a lot smoother.
 - Use your own custom spinner rather than the built-in spinners provided.

You can find the new features in the [dcc.Loading](https://dash.plotly.com/dash-core-components/loading) section of the dash docs.

I'll do a draft PR to apply a few new settings, and you can check it out by running the demo  app.   If you are interested in adding this,  I'd be happy to help fine-tune it.

### Describe the solution you'd like

As described above

### Alternative Solutions

None

### Additional context

None

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by Joseph-Perkins** [comment]
ok super! thank you so much @AnnMarieW 🙏 (also I'm sure @huong-li-nguyen will be very interested to see in more detail when back from holiday in about a week!)
