### ISSUE TITLE
trendline options None not works.

### ISSUE THREAD

**Issue by hwoarang09** [mckinsey/vizro#494]
### Description

using parameter,
px.scatter trendline None  not work.
other lowess, ols works.

### Which package?

vizro

### Package version

'0.1.16'

### Python version

3.11.5

### OS

window

### How to Reproduce

yearly_groups = df_korea.groupby(df_korea.index.year)
data = yearly_groups[['Magnitude']].count()
fig = px.scatter(data_frame=data,trendline=None)
fig.update_layout(width=800, height=600)
fig.show()

default trendline is None.

but

page_World_Year = vm.Page(
    id="World Year",
    title="Year",
    components=[
        vm.Graph(id="year_world", figure=year_w),
    ],
    controls=[
        vm.Parameter(
                      targets=["year_world.trendline"],
                     selector=vm.Dropdown(
                      options=['lowess', 'expanding', 'ols', None],
                multi=False,
                value='ols',
                     ))
    ]
)

it doenst work.

---------------------------error message----------------------
ValidationError: 17 validation errors for Dropdown
options -> 0
  value is not a valid boolean (type=value_error.strictbool)
options -> 1
  value is not a valid boolean (type=value_error.strictbool)
options -> 2
  value is not a valid boolean (type=value_error.strictbool)
options -> 3
  none is not an allowed value (type=type_error.none.not_allowed)
options -> 0
  value is not a valid float (type=type_error.float)
options -> 1
  value is not a valid float (type=type_error.float)
options -> 2
  value is not a valid float (type=type_error.float)
options -> 3
  none is not an allowed value (type=type_error.none.not_allowed)
options -> 3
  none is not an allowed value (type=type_error.none.not_allowed)
options -> 0
  invalid date format (type=value_error.date)
options -> 1
  invalid date format (type=value_error.date)
options -> 2
  invalid date format (type=value_error.date)
options -> 3
  none is not an allowed value (type=type_error.none.not_allowed)
options -> 0 -> __root__
  OptionsDictType expected dict not str (type=type_error)
options -> 1 -> __root__
  OptionsDictType expected dict not str (type=type_error)
options -> 2 -> __root__
  OptionsDictType expected dict not str (type=type_error)
options -> 3
  none is not an allowed value (type=type_error.none.not_allowed)

I think, 
through  print(fig),
i can find that, 
except trendline=None, 
all trendline option append new data to input data.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hello @hwoarang09, the right way to enter `None` as an option is to use the string `"NONE"`: https://vizro.readthedocs.io/en/stable/pages/user-guides/parameters/?h=none#basic-parameters.

So you would do this:
```
selector = vm.Dropdown(
    options=["lowess", "expanding", "ols", "NONE"],
    multi=False,
    value="ols",
)
```

Does that achieve what you're looking for?

**Comment by hwoarang09** [comment]
@antonymilne 
Thank you.!! it works. 
i have some question about vizro...

1. in vm.Card, i want blank line. like <br><br> or \n\n
i tried several things, but it didnt' work...

2. is there any function that filter index, not columns.
filter, parameter, ...anything.
   i think i should use parameter with target data_frame... and option with different premade dataframe.
   
   Thank you.!!

**Comment by huong-li-nguyen** [comment]
Hey @hwoarang09,

Good to hear! 🎉 

1) If you provide an empty line, it will automatically add space between the following line. If you want an additional blank line, you must use `&nbsp.` The `Card.text` is based on markdown, so referencing the [markdown syntax of adding blank lines](https://stackoverflow.com/questions/20543454/create-two-blank-lines-in-markdown) should work 👍 

It would look like this:

### Example
```
import vizro.models as vm
from vizro import Vizro

page = vm.Page(
    title="Card",
    components=[
        vm.Card(
            text="""
        # Heading

        This is a paragraph that starts on a new line.

        Here is another paragraph.

        &nbsp;

        The `&nbsp;` followed by a blank line gives a blank line.
        """
        )
    ],
)

dashboard = vm.Dashboard(pages=[page])

if __name__ == "__main__":
    Vizro().build(dashboard).run()
```

<img width="337" alt="Screenshot 2024-05-23 at 22 00 38" src="https://github.com/mckinsey/vizro/assets/90609403/2f4e96b0-db50-4001-86cc-375cd2f71688">


2) To be clear, would you like to filter the data frame provided to the charts via a row index instead of a column value? If yes, I think the simplest way of doing that is to create a column with row indexes and then continue using the `Filter` on that column.

Hope that helps! 🤞

**Comment by hwoarang09** [comment]
oh....make column with index value...good. Thank you!!

**Comment by antonymilne** [comment]
Thank you for the questions @hwoarang09 - closing this as completed now but please do raise another issue if you have any more questions!
