### ISSUE TITLE
Native chart animations not working in Vizro but in pure Dash

### ISSUE THREAD

**Issue by maxschulz-COL** [mckinsey/vizro#551]
### Description

Chart animations of for e.g. the px.icicle (https://plotly.com/python/icicle-charts/#icicle-of-a-rectangular-dataframe-with-continuous-color-argument-in-pxicicle) do not work in Vizro, but in pure Dash.

### Expected behavior

Would expect chart animation to work, and by that I mean the transitions one observes in the docs. One can also notice that the text size is not variable here in this example, but it is in the docs.

### Which package?

vizro

### Package version

0.1.18

### Python version

3.11

### OS

Mac

### How to Reproduce

```python
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
import numpy as np

df = px.data.gapminder().query("year == 2007")

page = vm.Page(
    title="My first page",
    components=[
        vm.Graph(
            figure=px.icicle(df, path=[px.Constant("world"), 'continent', 'country'], values='pop',
                color='lifeExp', hover_data=['iso_alpha'],
                color_continuous_scale='RdBu',
                color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop'])),
        ),
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()
```

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
Hello,

Could you explain what you mean by "native chart animation not working?" Do you refer to the font sizes not changing and the labels being hidden for certain areas? I've run the example above, but it runs as intended based on our chosen defaults.

It's important to note that we do not allow changing font sizes from a design best practice, as consistency in font sizes and setting a minimum font size for readability are important. The Vizro example works as this Dash example: https://plotly.com/python/icicle-charts/#controlling-text-fontsize-with-uniformtext

These are the defaults that cause that behaviour:

```
  uniformtext_minsize=12,
  uniformtext_mode="hide"
```

I would not allow for changing font sizes, but if you want more labels to be visible, you can control it by changing the default for the above arguments, e.g., by creating a custom chart and changing the minimum font size allowed or always showing the labels: `fig.update_layout(uniformtext=dict(minsize=11, mode="hide"))`.

**Comment by maxschulz-COL** [comment]
@huong-li-nguyen 

> Expected behavior
Would expect chart animation to work, and by that I mean the transitions one observes in the docs. One can also notice that the text size is not variable here in this example, but it is in the docs.

I see - I have to admit that this is a bit confusing as I suspected a bug on the Vizro side. I would generally expect charts to behave as in the plotly docs, especially when using `px` directly - maybe not from a coloring perspective, but certainly for chart animations when clicking into categories. 

I understand that we are trying to follow design best practices, but in many cases this seems also a matter of taste, or at least there is no one size fits all approach - I would argue that the [Vizro default for the px docs example](https://py.cafe/snippet/dash/v1?c=H4sIAIsohWYAA41VTW_jNhD9K4J6sAPYhCV_yQHYQ9tFTwWKPezFCgJaoixuKJJLUo7lRf57HynHdQ4BVj7YM_Pm681o_DOtdM3Tx1R0RlufnMTFatJBJ13CXHLqSvXBZKT2ciD8bCx3EWLOpWqs7kZAckV_C8LNV_WdGQJYmVKVqm4SCj9SM8_IkZlOqJrb6QP50XM7TMt04MwmlCb5YrEt04fgY9iRw-vUkX_xa1qqBI8XXnJapv8MSSOs80lAlelstFYa2RVX3tH9qAkPIvxtmWmvId6fRhx7yymqEpWoJJ_WzQzhfEv30P2plfNMedT2qq2sUdQsmVRaeRESTKLQK2-HydMsOTHZc0cnRpvJtZb7p9JSWzqRouFfzkAkrT5x-xzYoPuJcPqZSdMyRPrE93lM3OvePbuKgYLJ1_qP_tNc9_hO1EYL5akyhCFtILNu9rdqUP4rF8cWpAV1aOHp4eEu8vvvUF2cDObJXHvQzNbjgP56F6dhHCA_fD0By4wBIq4Ghn3ohaynN98HrINrS5XOUst_9MLyLowOuznq43r9ThckI1kRYX4wYXWDGRKCfxP8NX30tuezlNfCf1HsIAEZNWbwrVZwMIOuRc3npwXJN2QBX8kG3fv08WdqtfZfNaL8fA9vIc3SqkWxlsN9_wsWzw6OexhHKtPH7YZk212-WufFcpEVxfZTPziFrYOAhogZ0rent9nngfMlKfLFdr3aZptdkWXLXwh8Ty_xZx9ShM_bLG2E5KB8_wROdPUSRKy-BxJ-vyUtqH5MMpZt83yz3CxX2Y4tiqLa1lVTrFe7Zp03eYVBK6U987yeh_yOYmogulQHKdQLt5RmpCB5qSpWtVyKQwDsAqDi1otGUJov8hXJI6ZlFj3PlbYdk-IS3JdkGU1SVC-UFliJ7biFcATRJBulOTvOj1bUcMgQDPGj9oAZO48bML-7ECgplhgRlbb8gxHON2PrO_mpscORwEn4YMfKoqorAJPA-0rXo08jmUMHS0jLqzQPpAh1DHGhxw2tFQsQtDieUxA277hn8WDQLTpDcOFdzdSRW7zkwTW2-12o7ywPzlmI3zH70hvHGhQAJ7IuleLOz5kbVCX0jYN4roOE12MVTm8o_RZ0_AsILeSjPCCxF1UAbO8VkcaYCRMK6vG1a703gZRY9vhSztEK772QAY1FIEY7HyP5y3UXgA17i3JjJRgo7Jbj4kau0F8oFYvSG6-1BGizI-vg5sQ52LPYGlaZVcKj_IJgwaAYDALM-RkWJ3DmKUWyGN1fRobf8_dWgvrlSATkeJHieONFeuX25cJ7FHMd5ytWzP-f-iIM-sYodiGvcxJH7O0_4fCUZoEHAAA) looks less good and less clear than the example in the docs. Maybe something to think about relaxing? In the end the user can very easily add this back in 🤔 ?

**Comment by huong-li-nguyen** [comment]
In the end, Vizro is very opinionated when it comes to design decisions. In this case, I would even argue that it's not a matter of taste but a common rule. If you are looking for UI best practices for minimum font sizes, 12-16px is the standard number, but going below 12px is not recommended (not only from us but more generically). Our designer decided this would be 12px, which is acceptable because you can barely see smaller font sizes on bigger screens. 

So, in this case, I believe the current implementation is correct. We set our default minimum font size to 12px, and if the user wants to deviate from our design recommendation, they can go below, but they need to configure it themselves.

But if you strongly disagree, feel free to open a discussion :) I just wanted you to understand why we should not go below a certain font size. In this case, my preference for building dashboards is also our current default but open to changing it if our team agrees.

**Comment by maxschulz-COL** [comment]
I get why we do not want to go below a certain font size, that makes sense, but I wonder if this requirement is worth changing a `px` chart in such a fundamental way.

Again, I was so confused as to why animations did not work that I opened an issue on the plotly forums - I wonder if a template should have the right to be so opinionated when it comes to changes default behaviour of charts.

Besides that, less important, I also think that default simply does not look good - do you find the above posted example actually better and more readable?

Will definitely not start a discussion on that :) Was just something I observed when actually using this chart in Vizro.

**Comment by huong-li-nguyen** [comment]
Let's pick it up in the next call - I'll close that issue for now :)
