### ISSUE TITLE
[Bug in docs] Vizro-AI model support is inaccurate

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#568]
### Description

The docs say that one of the models we support is `gpt-4-turbo` but when I pass this into `VizroAI(model="gpt-4")` I'm returned 
> ValueError: Model gpt-4 not found! List of available model can be found at https://vizro.readthedocs.io/projects/vizro-ai/en/latest/pages/explanation/faq/#which-llms-are-supported-by-vizro-ai

[So the page](https://vizro.readthedocs.io/projects/vizro-ai/en/latest/pages/user-guides/customize-vizro-ai/#supported-models) needs updating, as does the code that returns that error (since that URL isn't really correct either -- it just directs the reader onwards to https://vizro.readthedocs.io/projects/vizro-ai/en/latest/pages/user-guides/customize-vizro-ai/#supported-models)

### Expected behavior

The model should work if it's given in the docs. 

Package versions:
* `vizro                     0.1.18`
*  `vizro-ai                  0.2.0`

### Which package?

vizro

### Package version

0.2.0

### Python version

3.10

### OS

MacOS

### How to Reproduce

asfdfasdafd

### Output

Too many questions :(

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by lingyielia** [comment]
@stichbury Thanks for reviewing! `gpt-4` was not included in the code, so `VizroAI(model="gpt-4")` returns error. I created a PR to add all capable models and their aliases.
