### ISSUE TITLE
[Bug] Accordion titles do not update correctly if page is used within several accordions

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#573]
### Description

If the same page is used within several accordions, the accordion titles do not update correctly when navigating to that page.

### Expected behavior

Let's say I have a configuration like this - the page with the title "Line" is used in several accordions sub-groups. If I switch from one icon to the other, I would expect the accordions and their respective titles to update correctly as well. However, that doesn't seem possible right now as the accordion build doesn't get refreshed given that one goes from `localhost:8050/line` to `localhost:8050/line` if one switched from one icon to the other.

```
dashboard = vm.Dashboard(
    pages=[line, scatter],
    navigation=vm.Navigation(
        nav_selector=vm.NavBar(
            items=[
                vm.NavLink(
                    label="Deviation",
                    pages={"Deviation": ["Line", "Scatter"]},
                    icon="Planner Review",
                ),
                vm.NavLink(
                    label="Time",
                    pages={"Time": ["Line"]},
                    icon="Timeline",
                ),
            ]
        )
    ),
)
```

### Which package?

vizro

### Package version

newest

### Python version

3.9

### OS

-

### How to Reproduce

-

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
The second point (each page can appear 0 to 1 time in navigation) wasn't so clear I think. Let's quickly discuss in our call, because then I can show you the current code set up which makes it a bit clearer why above might be useful.

It can definitely be solved by duplicating the page and just provide different `paths`. If we decide/align that this is the way to go (which I am fine with this restriction), I do think we need validation because currently it just looks like it's malfunctioning and I also couldn't remember anymore what we actually aligned on 😅

**Comment by antonymilne** [comment]
@huong-li-nguyen Please could you post some kind of conclusion here in case we come back to it in future?

**Comment by huong-li-nguyen** [comment]
Conclusion:
- We only allow a 1:1 mapping between a page and an accordion / icon
- Validation should be added if easily enabled (check that a page is only mapped once to an accordion and/ or icon)
