### ISSUE TITLE
Is There a Way to Get the JavaScript Code for a Given Vizro app.py? 

### ISSUE THREAD

**Issue by at-eez** [mckinsey/vizro#575]
### Question

Is There a Way to Get the JavaScript Code for a Given Vizro app.py? I would like to integrate a Vizro-Dash dashboard page into a React-based multi-page dashboard. Wondering if it's possible to implement this? 

### Which package?

vizro

### Python version

3.12

### OS

Windows

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Hello @Layman-Bebop and thank you for your question! Vizro is built on top of Dash, and the answer here is the same as it would be for Dash: depending on exactly what you want to achieve this may or may not be possible. The answer is pretty [well covered in the Dash documentation](https://dash.plotly.com/integrating-dash).

It's unfortunately not possible to directly convert a Dash dashboard into pure JS code. The options are:
1. Embed as a React component - this is the best solution and probably what you want to do but requires Dash enterprise, which costs 💰
2. Embed as an iframe - feels a bit hacky but in practice can actually work very well. I've seen people do this before successfully and you wouldn't even guess it was an iframe just from using the website. This is quite a new feature, not documented or fully worked out yet but It's also possible to pass information into Vizro using query parameters sent through the `iframe src`, a bit [like this](https://community.plotly.com/t/passing-state-to-dash-app-via-iframe/76496)
