### ISSUE TITLE
Custom data does not get picked up if directly defined inside custom chart

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#584]
### Which package?

vizro

### Package version

0.1.18

### Description

If this is supposed to be like this, then I think we need to raise an error earlier or document it somewhere. Optimally this should work though: https://py.cafe/huong-li-nguyen/vizro-bug-filter-interaction

If the custom data argument is defined directly inside the custom data chart code, it doesn't get picked up (see example app and screenshot). So this **does not work**:

```
@capture("graph")
def custom_chart(x: str, y: str, color: str, data_frame: pd.DataFrame = None):
    fig = px.box(
        df_gapminder,
        x=x,
        y=y,
        color=color,
        custom_data=[color],  # this does not get picked up if defined here?
    )
    return fig
```

It only gets picked up if the custom_data argument is part of the custom data function so **this works**:

```
def custom_chart(x: str, y: str, color: str, custom_data: str, data_frame: pd.DataFrame = None):
    fig = px.box(
        df_gapminder,
        x=x,
        y=y,
        color=color,
        custom_data=[custom_data],
    )
```

<img width="1223" alt="Screenshot 2024-07-14 at 20 09 33" src="https://github.com/user-attachments/assets/a9d9ed8d-6e27-4450-8ba1-8ccd42dd564c">

Is it supposed to be like this? If yes, shall we raise a validation error earlier?

### How to Reproduce

https://py.cafe/huong-li-nguyen/vizro-bug-filter-interaction

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Here is a [PR link](https://github.com/mckinsey/vizro/pull/552) where the issue is addressed.
