### ISSUE TITLE
Potential CSS issue with KPI card and AGGrid

### ISSUE THREAD

**Issue by maxschulz-COL** [mckinsey/vizro#610]
### Which package?

vizro

### Package version

latest

### Description

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/90628efa-07a6-4d6c-aafc-e8d4194949cd">

Having a KPI card above the AgGrid seems to be a problem.

### How to Reproduce

.

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by maxschulz-COL** [comment]
@nadijagraca Could you maybe investigate if you find the time? 🙏

**Comment by huong-li-nguyen** [comment]
Has this been solved already? @nadijagraca

**Comment by huong-li-nguyen** [comment]
This doesn't seem to be an issue anymore: https://py.cafe/app/huong-li-nguyen/CSS%20bug

@maxschulz-COL - do you have the configuration for the above bug? I can double-check with that configuration as well, but  from the pyCafe example it seems fine.
