### ISSUE TITLE
(VizroAI) Support for AzureChatOpenAI and most updated models for OpenAI (such as GPT-4o mini)

### ISSUE THREAD

**Issue by at-eez** [mckinsey/vizro#625]
### Question

Hi Vizro AI Team, OpenAI has recently updated there newest gpt-4o-mini model and made gpt-3.5-turbo outdated. Will this update be reflected in Vizro AI? Also, I noticed the part about working with Azure OpenAI is deleted. Is this under development? Will user be able to use Azure OpenAI endpoints to conduct Vziro AI tasks?

Many thanks!

### Which package?

None

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by Layman-Bebop** [comment]
And will Vizro-AI support opensource LLMs such as llama 3.1 as well?

**Comment by maxschulz-COL** [comment]
Hey @Layman-Bebop!

Thank you very much for your question! 

Yes we are indeed going to add `gpt-4o-mini` to the pre-defined models and generally update our pre-defined strings.

However, did you know you could configure any model already yourself? The second example in the below link shows how to choose any `OpenAI` model, not just the pre-configured ones!

https://vizro.readthedocs.io/projects/vizro-ai/en/vizro-ai-0.2.0/pages/user-guides/customize-vizro-ai/#customization-at-initialization

As for AzureOpeAI, we are temporarily removing it until a bugfix can be found for an existing issue. @lingyielia can elaborate here.

And finally, yes, we are actively working on supporting open source model, and the release of that functionality is not so far away, so stay tuned for this :)!

**Comment by Layman-Bebop** [comment]
Thank you very much @maxschulz-COL ! Will stay tuned!

**Comment by lingyielia** [comment]
Hi @at-eez , with our new release we now support more LLM vendors and models: https://vizro.readthedocs.io/projects/vizro-ai/en/vizro-ai-0.3.0/pages/user-guides/customize-vizro-ai/

In theory, any model that supports langchain `structured_output` would work with Vizro-AI. I'm closing this issue now. Do let us know if you have additional findings! :)
