### ISSUE TITLE
Slider text value is not completely visible

### ISSUE THREAD

**Issue by petar-qb** [mckinsey/vizro#680]
### Which package?

vizro

### Package version

0.1.21

### Description

When Vizro control selector is a Slider (I didn't test it with other numerical selectors) and when values are `float` numbers, slider values are cut off on the UI.

### How to Reproduce

The following code causes the issue for me:

```py
import pandas as pd
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro


df = pd.DataFrame({
    "col_1": [0.1, 0.2, 0.3, 0.4, 0.5],
    "col_2": [10, 20, 30, 40, 50],
})


page = vm.Page(
    title="My first page",
    components=[
        vm.Graph(
            id="graph_id",
            figure=px.scatter(df, x="col_1", y="col_2"),
        ),
    ],
    controls=[
        vm.Filter(
            column="col_1",
            selector=vm.Slider()
        ),
        vm.Parameter(
            targets=["graph_id.title"],
            selector=vm.Slider(min=0.0, max=1.0, value=0.75),
        ),
    ],
)

dashboard = vm.Dashboard(pages=[page])

if __name__ == "__main__":
    Vizro().build(dashboard).run()
```

### Output

<img width="521" alt="image" src="https://github.com/user-attachments/assets/633bb0ef-fd88-4c87-9c2c-29a6868e7d90">

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by huong-li-nguyen** [comment]
https://github.com/mckinsey/vizro/issues/361
