### ISSUE TITLE
how to update layout dynamically?

### ISSUE THREAD

**Issue by vks2** [mckinsey/vizro#684]
### Question

how to make this code work if the layout and cards in it are generated dynamically ( from sql queries)? page = vm.Page(
    title="Api docs",
    layout=layout,
    components=[
        vm.Graph(
            id="scatter_chart",
            figure=px.scatter(df, x="Количество методов", y="Значений на сегодня", color="Группа показателей"),
        ),*cards,
    ],
    controls=[
        vm.Filter(.....)]))). now i'm going through global variables and refreshing  but it's not the best way. thanks much

### Which package?

None

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @vks2 and thanks for the great question.

There's an example in Vizro docs where, based on the user's input, dynamic number of [dbc.Card](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/card/) components is rendered on the UI. You can find the example [here](https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-figures/#dynamic-number-of-cards) or start playing instantly with the example by visiting the [vizro dynamic card py.cafe example](https://py.cafe/vizro-official/vizro-dynamic-cards).

I hope this example helps you solve your case without having to refresh the page (let us know the results). 😃

**Comment by vks2** [comment]
works good, thanks much
