### ISSUE TITLE
[Docs] Consider replacing iframe example with screenshot

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#698]
We currently have an iframe of a dashboard running here: http://127.0.0.1:8000/en/stable/pages/tutorials/first-dashboard/

![Screenshot 2024-09-12 at 12 07 50](https://github.com/user-attachments/assets/ade94dd4-72cb-471e-b176-fe116e56c30f)

Personally, it takes too long for me to display the dashboard due to the installation. I would prefer if we have a similar view as in the other doc examples - with the option to go to the pyCafe example. Because everytime I switch to another page and then go back, it does the install step again. 

![Screenshot 2024-09-12 at 12 05 24](https://github.com/user-attachments/assets/e1d007c6-b270-4181-83f6-2e2a34c398fd)

WDYT?

**Comment by petar-qb** [comment]
Just to say that I share the same opinion as you Li about our docs UX and py cafe.
I agree that we should not set the py cafe as the default example. However, do you think that setting the py cafe example as an iframe alongside the `app.py`, `app.yaml` (tab) is a good solution (with keeping the "Run and edit this code in Py.Cafe")? 

Just to say that I share the same opinion as you Li about our docs UX and py cafe.
I agree that we should not set py cafe iframe example as the default one. However, do you think placing the py cafe example as an iframe next to `app.py`, `app.yaml` (tab) is a good solution? (while keeping "Run and edit this code in Py.Cafe") in the same place it is now)

**Comment by huong-li-nguyen** [comment]
I think it depends how it looks like. Personally, I would be satisfied with just a screenshot, as we have in all other examples. The screen sizes within the tabs are usually not very large, so if the iframe is placed inside a tab and the screen size is too small for any meaningful interaction, I would prefer using a screenshot.

Ultimately, users always have the option to access the interactive example, but I don't think we need to present it to them right from the start.

**Comment by stichbury** [comment]
Unfortunately, iframing py.cafe inside a tabbed section like our other examples looks rubbish (the view size is too small). @maxschulz-COL and I rejected this as a solution.

I see your point about the load time in the iframe as it stands. I think the solution is probably to follow all the other examples: first the code and below it, the link through to py.cafe. Readers get their first taste of how we present the rest of the examples by way of this introduction and we could add a screenshot too to align with other examples.

**Comment by huong-li-nguyen** [comment]
I can do it 👍
