### ISSUE TITLE
Contribute `Dot plot` to Vizro visual vocabulary 

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#708]
## Thank you for contributing to our visual-vocabulary! 🎨 

Our visual-vocabulary is a dashboard, that serves a a comprehensive guide for selecting and creating various types of charts. It helps you decide when to use each chart type, and offers sample Python code using [Plotly](https://plotly.com/python/), and instructions for embedding these charts into a [Vizro](https://github.com/mckinsey/vizro) dashboard.

Take a look at the dashboard here: https://huggingface.co/spaces/vizro/demo-visual-vocabulary
The source code for the dashboard is here: https://github.com/mckinsey/vizro/tree/main/vizro-core/examples/visual-vocabulary

## Instructions

0. Get familiar with the dev set-up (this should be done already as part of the initial intro sessions)

1. Read through the [README](https://github.com/mckinsey/vizro/tree/main/vizro-core/examples/visual-vocabulary) of the visual vocabulary

2. Follow the steps to contribute a chart. Take a look at other examples. This [commit](https://github.com/mckinsey/vizro/pull/634/commits/417efffded2285e6cfcafac5d780834e0bdcc625) might be helpful as a reference to see which changes are required to add a chart.

3. Ensure the app is running without any issues via `hatch run example visual-vocabulary`

4. List out the resources you've used in the [README](https://github.com/mckinsey/vizro/tree/main/vizro-core/examples/visual-vocabulary)

5. Raise a PR 

**Useful resources:**
- Dot plots: https://plotly.com/python/dot-plots/
- Data chart mastery: https://www.atlassian.com/data/charts/how-to-choose-data-visualization

**Comment by njmcgrat** [comment]
can I do this chart please?
