### ISSUE TITLE
Participate in `FigureFriday` and create a Vizro app (for multiple participants)

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#715]
### You will learn 📚:

- Navigating through technical documentation
- Working with Plotly charts and customizing them via post update calls
- Utilizing PyCafe for development and building your own portfolio
- Creating your Vizro app from scratch

--- 

## Instructions
1. **Explore [Plotly's FigureFriday](https://community.plotly.com/tag/figure-friday) and choose any week you would like to participate in.** Reviewing previous weeks can inspire your potential submissions. Your task is to take the relevant data set and enhance the existing Plotly visualization. This could involve creating a new chart or improving the current chart code.

2. **Create an account on pyCafe if not already done:** https://py.cafe/ Fork the [Vizro project template](https://py.cafe/snippet/vizro/v1#c=H4sIAAGu-2YAA61VTW_jNhD9K6xyqAPIcpzttoUBt2jTdvfQw2IPuwc7CGhpZBGhSJak7ChB_nvfUHYaOwkSoCsdRA7n481w3uguK21F2Sw7EV_UrbdCBSGNsI7MONjOlySitfpaRVFbL0pPMiqzFq2tOi29qGSUYqNCJ7W6xZE1QjqnVZnWoViaE1E2VF4L20XRxOjCbDJZq9h0q6K07aQtr5UJ1E82KTwHaa0noUxthVyxVQLGjqSpBmePfSW7Ariq2FBly1AoOyEzCVGuNE2SR4i7lkxMoIBpaVTrrI9AzsZO26j7gm6cp4D8g3A3S1N72w4KYqe9A3Jgi0KQTjablh1XtZjDvODCFMqrMDplsZNrwsGmLT5hNVoagSeqqGm-zIbKo3Sf-gtZ0zLLh3Mte2Q6h9HfaTVae1XNF4uzXEwvc7E4z8X54--7XLx7-GLh7faqVeaqIbVuIgJNfzhDZtnpzj_q76xBXcJ8MUj4QbgL6asdxv0T6YY9pPfggJ-TkxPxtZGRuycl8-tTnd--aVcde38q-SydqnQvAul6HMhvELMhXFSgdgW5rUXZhWhbdUsVIoZmZZF2QOcJFK2LFMRYbNGp3G1sagiKjFdWG2lKbMAdhs0dRkGtjUALkVeEQ9hGO2RGotZ0o9CNqYNDKTW3Zo7rhnMzJsNbxvBK1kfV31_j_7i0D4mI3KDHpxd7nqX7_D6w6sduJVIjcxHqzqMoPhHVtzu4SM-TJhlQLYsKFuLCmujVqkspCAlmS72VfRBb0ug_-m6A9ygVfhpPNYC_Oi8ODI_q8cFL14xAmGWGksdI_qpspI-wEbVad57m4OnuaFTVubhhVXJSX2ky69iwZg-ZowjZVmHCsKi02npWdVQqCuDTy5EbFeJzYVlu1162R4HfEOTygb2orNXgLkL-pTRnAauuNQdmOSM6Ph4y2mf5vM4BoFOOmibZA1OGcfbHfjvizgAY_lxCM_XN6LRYdUpXower08J3hmdilmee_umUJ57MAb-gdKO_zM-KaTH9mef9irTdYi6Crcw9UCQSz17pFUSgFzoBeejETg2iBUxl8oFbEfQeZjfWri9KnqvGd3U9R4Afiyn6H-OmvE5AYu_4H5gMsAXrvijaZrNa6kB5RpWKfyaSZrPoO0hcYi5MXI8RUNF4c1acwyuMh6Gdze6yHZRsdo5UrY2fLVze7YNhOEO7bFAdT1BaPJzgxxUo4jDVPptN35_lGUbS12H7bth9TEN92KoKZrXS9Du8YtYx6aQy5F-IwKrj1aALFSfZb5bdX97nT1G8APE_O5SrcP2h9Ruyez2jHcLXstkn8jz84eeHKv70_i0xQQGIpX4t6F6Po_J7n6eqoo8Xl_f_AnooWrNWCQAA) to your account. This will allow you to customize the Vizro app.

4. **Get familiar with Vizro's app configuration and add some changes.** Refer to [Vizro's documentation](https://vizro.readthedocs.io/en/latest/pages/user-guides/install/)  to understand how to configure the models. Here are some ideas for modifications:

    - [ ] Add a Graph to your Page and [insert a Plotly chart](https://vizro.readthedocs.io/en/latest/pages/user-guides/graph/#insert-plotly-chart)
    - [ ] Add a Graph to your Page and [insert a custom Plotly chart](https://vizro.readthedocs.io/en/latest/pages/user-guides/custom-charts/)
    - [ ] Add your Page to the Dashboard
    - [ ] Add a title to your Dashboard
    - [ ] Add a logo to your Dashboard e.g. take the vizro logo [here](https://github.com/mckinsey/vizro/blob/main/vizro-core/examples/dev/assets/images/logo.svg): 
    - [ ] Add controls to your Dashboard (Filter or Parameter)
    - [ ] Add a second Page with a AgGrid to your Dashboard
    - [ ] Experiment with the Navigation e.g. create a NavBar
    - [ ] (Optional) Upload your app on py.Cafe and submit your app to the Figure Friday challenge

**Useful resources:**
- Vizro documentation: https://vizro.readthedocs.io/en/latest/pages/user-guides/components/
- Existing Figure Friday submissions using Vizro: https://py.cafe/huong-li-nguyen
- First tutorial on dashboards: https://vizro.readthedocs.io/en/stable/pages/tutorials/explore-components/
- Plotly documentation: https://plotly.com/python/plotly-express/
- Plotly layout: https://plotly.com/python/reference/layout/

**Comment by Mahsatr** [comment]
Hi @huong-li-nguyen I'm interested to work on this and create a Vizro dashboard from scratch and learn. Thank you!

**Comment by sylviebartusek** [comment]
Hi! I would love to work on this. My github username is `sylviebartusek`.

**Comment by KhushaliP** [comment]
Looking forward to creating a dashboard for the FigureFriday challenge!

**Comment by Anika090602** [comment]
Hi , I would like to work on this and learn.

**Comment by mviswan34** [comment]
Hi Li, Looking forward to work on PyCafe and Vizro. :)

**Comment by cliu26** [comment]
Hi, would love to work on this!

**Comment by YufeiYYY** [comment]
Hi, I would love to work on this

**Comment by SanchitaRane** [comment]
Hi, I would I like to work in this.

**Comment by huong-li-nguyen** [comment]
Hey all - so happy you guys want to do this one! Feel free to tackle this :)

**Comment by huong-li-nguyen** [comment]
If some others decide to do this later, anyone can take this ticket on. It's not limited to a number of participants as everyone would independently work on your pyCafe project :) Please add your pyCafe project links here, so we can eventually add it to our docs and give you some credits 👍

**Comment by vpogudina** [comment]
Hi, I would like to work on this too :)

**Comment by Mahsatr** [comment]
> Hi @huong-li-nguyen I'm interested to work on this and create a Vizro dashboard from scratch and learn. Thank you!

My Py.Cafe link for the APP: https://py.cafe/app/fatemeh.taer74/vizro-iris-explorer

**Comment by ManaliTanna** [comment]
HI, I am working on this: https://py.cafe/mut8188/vizro-visualization-demo

**Comment by KhushaliP** [comment]
Hi, this is my [code link](https://py.cafe/KhushaliP/vizro-music-trend-analysis)
and the [dashboard link](https://py.cafe/app/KhushaliP/vizro-music-trend-analysis)

**Comment by huong-li-nguyen** [comment]
Hello everyone,

please let me know if you want me to add your example to our docs here: https://vizro--797.org.readthedocs.build/en/797/pages/examples/your-examples/#examples-on-github-or-pycafe

For this please:
- Add a link to your pyCafe dashboard as comment here :)

@Mahsatr - the link unfortunately didn't seem to work - could you double-check?
@ManaliTanna - could you check if you pushed your changes? When I click on the link it seems to show our default vizro example :)
@KhushaliP - beautiful example! I've added it to our docs and linked to your Github profile 🚀

**Comment by Mahsatr** [comment]
Hi @huong-li-nguyen - here is the link to my Py.Cafe dashboard: [Dashboard Link](https://py.cafe/app/fatemeh.taer74/Figure%20Friday%202024%20-%20week%2040)

And I believe this should be the link to my code: [Code Link](url) https://py.cafe/fatemeh.taer74/Figure%20Friday%202024%20-%20week%2040

**Comment by huong-li-nguyen** [comment]
Hello @Mahsatr - this is a great Dash app, which I think you should definitely submit to the FigureFriday thread for that week's challenge! :) 🚀

To be added to our documentation unfortunately, you would have to use Vizro to build the Dash app though. Vizro in the end returns a Dash app, but automatically styles the app (see some of the documentation links in this ticket).

**Comment by Mahsatr** [comment]
Hi @huong-li-nguyen - Thank you! I will definitely submit it to the FigureFriday Week 40 thread. :)

Regarding the documentation, I would love to write it up and experiment with Vizro too to be added to the documentation if that's something that could be done.

**Comment by huong-li-nguyen** [comment]
Hey @Mahsatr , what you could do is convert your Dash app to a Vizro app with the help of our documentation :) 

It should be fairly straightforward, as you already have all the code. Afterwards we can always add your example to our documentation, there is no deadline :)
