### ISSUE TITLE
Fix capitalisation of `Jupyter notebook` to `Jupyter Notebook`

### ISSUE THREAD

**Issue by huong-li-nguyen** [mckinsey/vizro#723]
- Do a quick search and find for any `Jupyter notebook` version and replace with `Jupyter Notebook` where suitable

**Comment by bhavanaeh** [comment]
Hi @huong-li-nguyen I'd like to help here if its up for grabs :)

**Comment by huong-li-nguyen** [comment]
Yes, that would be great @bhavanaeh 👍

**Comment by stichbury** [comment]
Thanks for your contribution @bhavanaeh -- this is now ready to merge and will go in automatically soon.
