### ISSUE TITLE
Is it possible to connect with other dash component?

### ISSUE THREAD

**Issue by yaoyi92** [mckinsey/vizro#727]
### Question

Very nice package!
I am wondering is it possible to use vizro with other components of dash?
For example, the components in dash_bio. https://dash.plotly.com/dash-bio/nglmoleculeviewer

### Which package?

vizro

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @yaoyi92 and thanks for the great question! 

Vizro is built on top of Dash which makes it really flexible. In case you want to add a custom component to the Vizro dashboard, this ([link to Vizro docs](https://vizro.readthedocs.io/en/stable/pages/user-guides/extensions/)) is probably the best documentation starting point. As `dash_bio` creates a standalone chart (and not the native Plotly chart), it means that the best way to wrap the dash_bio chart into the Vizro dashboard is to utilise the [custom figures](https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-figures/) feature.

Here's an example on how to add a `dash_bio.NglMoleculeViewer` into Vizro dashboard. (example similar to this one -> https://dash.plotly.com/dash-bio/nglmoleculeviewer#nglmoleculeviewer). 

There are a few useful Vizro documentation links shared in the code below. You can find them in the comments that start with `"# TODO - Docs: "`.

```py
"""Dev app to try things out."""
import dash_bio as dashbio
import dash_bio.utils.ngl_parser as ngl_parser
import pandas as pd

import plotly.io as pio

import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from vizro.models.types import capture


data_path = "https://raw.githubusercontent.com/plotly/datasets/master/Dash_Bio/Molecular/"

# TODO - Docs: custom figures -> https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-figures/
# TODO - Docs: Additional example on how to customise custom figure argument (pdb_id) with Vizro Parameter
# -> https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-figures/#dynamic-number-of-cards
@capture("figure")
def custom_bio_molecule_figure(data_frame, pdb_id):
    data_list = [ngl_parser.get_data(data_path=data_path, pdb_id=pdb_id, color='red', reset_view=True, local=False)]

    return dashbio.NglMoleculeViewer(
        id="ngl_molecule_viewer_id",
        data=data_list,
        molStyles={
            "representations": ["cartoon", "axes+box"],
            "chosenAtomsColor": "white",
            "chosenAtomsRadius": 1,
            "molSpacingXaxis": 100,
        },
    )


page = vm.Page(
    title="Action with clickData as input",
    components=[
        # Here we send the empty pd.DataFrame() object to figure "data_frame", because the dashbio.NglMoleculeViewer "data" argument is not in the plotly standard format.
        vm.Figure(id="my_bio_figure", figure=custom_bio_molecule_figure(data_frame=pd.DataFrame(), pdb_id="1BNA")),
    ],
    controls=[
        # TODO - Docs: Vizro parameters -> https://vizro.readthedocs.io/en/stable/pages/user-guides/parameters/#dynamic-data-parameters
        vm.Parameter(
            targets=["my_bio_figure.pdb_id"],
            selector=vm.Dropdown(options=["1BNA", "MPRO", "PLPR", "5L73", "NSP2"], value="1BNA", multi=False),
        ),
    ]
)

dashboard = vm.Dashboard(pages=[page], theme="vizro_light")

if __name__ == "__main__":
    Vizro().build(dashboard).run()
```

P.S. The `dashbio.NglMoleculeViewer` component is not a native Plotly chart, which means its background color cannot be changed directly via global `plotly.io (pio)` templates. However, you can synchronise the background color of the NglMoleculeViewer with the Vizro application's background (including theme switching) by [adding custom CSS](https://vizro.readthedocs.io/en/stable/pages/user-guides/assets/).

For the example above, your custom CSS file might include the following styles:
```css
#ngl_molecule_viewer_id > canvas {
    /* rgba(0, 0, 0, 0) makes the background colour transparent */
    background-color: rgba(0, 0, 0, 0) !important;
}
```
