### ISSUE TITLE
Replace the use of "provide" with a simpler alternative as per Vale recommendation

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#735]
Vale recommends use of a simpler alternative to "provide"

<img width="606" alt="image" src="https://github.com/user-attachments/assets/0b724546-86e4-4a8c-8063-496c3fa9b5e4">

Task: Search across Vizro docs (vizro-core and vizro-ai) for instances of provide and replace with discretion.

If there are genuine cases where lower case python is more appropriate, use the following to switch Vale off/on in situ

```markdown
<!-- vale off -->
Legitimate use of provide
<!--vale on-->
```

**Comment by i-lahari** [comment]
Hello, I'd like to work on this. Can you please assign this to me.

**Comment by i-lahari** [comment]
Hello @antonymilne,

I apologize for the delayed response. I have just returned from GHC and haven't had the chance to check my notifications. I've made the necessary changes on my local machine, but I'm encountering some issues while creating the pull request. Please give me 2 days to figure out the problem with my GitHub.

**Comment by antonymilne** [comment]
Hi @i-lahari, no worries at all for the delay - welcome back! And thank you for your interest in contributing 🙏 Just let us know if you need any help raising the PR.

**Comment by stichbury** [comment]
Resolved by https://github.com/mckinsey/vizro/pull/848
