### ISSUE TITLE
Fix capitalisation in page titles and subheads to follow sentence-style as per Vale suggestion

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#736]
Vale catches all instances of headings/subheadings (anything preceded by `#` in markdown) where the capitalisation is not sentence style. That is, it'll flag "Do This Thing" and suggest instead "Do this thing". There will be suggestions across the Vizro docs, but not all of these will be valid because sometimes we are using proper nouns (e.g. for the word Notebook) and sometimes it's a code capitalisation.

<img width="572" alt="image" src="https://github.com/user-attachments/assets/d9166850-915e-422c-9de2-1ca5ad688f5d">

Task: Search across Vizro docs (vizro-core and vizro-ai) for instances of provide and replace with discretion.

Generally, if the capitalisation is genuine it'll be because we are using a technical term, and the best approach is to add it to the [`Headings.yml` style](https://github.com/mckinsey/vizro/blob/main/.vale/styles/Microsoft/Headings.yml).

**Comment by upekesha** [comment]
I'd like to work on this

**Comment by upekesha** [comment]
@stichbury I need some help understanding the task.   
I see the vizro-ai and vizro-core. What do you mean by "search for instances of provide and replace with discretion"?
 
i see [Headings.yml style](https://github.com/mckinsey/vizro/blob/main/.vale/styles/Microsoft/Headings.yml). has all the exceptions listed. Am I modifying this file or a different file?
