### ISSUE TITLE
Correct all mentions of Py.Cafe

### ISSUE THREAD

**Issue by stichbury** [mckinsey/vizro#750]
We have generally referred to PyCafe as Py.Cafe throughout.

I've confirmed with the PyCafe team and they'd rather use:
* PyCafe to describe their organization 
* [https://py.cafe](https://py.cafe) to talk about the site itself

The best way to fix this would probably be to grep through the docs content (`vizro-core` only as we don't use it in `vizro-ai` examples) for Py.Cafe.

It would make sense also to add a line to the `Terms.yml` file in the [Vale styles](https://github.com/mckinsey/vizro/blob/main/.vale/styles/Microsoft/Terms.yml):

```yml
Py.Cafe: PyCafe
```

**Comment by LydiaPitts** [comment]
Hello! I would like to work on this issue!

**Comment by LydiaPitts** [comment]
@maxschulz-COL The issue notes to change just the vizro-core and adding anote to Terms.yml file, and I've done so but I'm also seeing reference in Headings.yml, general-question.yml, and bug-reports.yml. Should I change these as well, even though they are not explicitly noted? If so, I'd love a better understanding of headings.yml. It seems like it's a config for headings, but would be good to know before I change it!

**Comment by LydiaPitts** [comment]
Hello! I'm seeing failures in my PR: 
- https://github.com/mckinsey/vizro/pull/784
- issue: https://github.com/mckinsey/vizro/actions/runs/11185441838/job/31098316378?pr=784
I'm not sure if the changelog needs to be updated, or how to go about it in my codespace? 

Also, in https://vizro.readthedocs.io/en/stable/pages/explanation/contributing/#develop-on-github-codespaces, it notes "Add your name to the [list of contributors](https://vizro.readthedocs.io/en/stable/pages/explanation/authors/) (source file vizro-core/docs/pages/explanation/authors.md)." Is this something I should do?

**Comment by LydiaPitts** [comment]
Connected via conference meeting! It should be resolved and ready for review!

**Comment by stichbury** [comment]
Fantastic work. [PR is set to auto-merge soon](https://github.com/mckinsey/vizro/pull/784). Closing this ticket with much gratitude! 🚀
