### ISSUE TITLE
Can we add a live update feature?

### ISSUE THREAD

**Issue by Bye-legumes** [mckinsey/vizro#76]
### What's the problem this feature will solve?

I find this tool very easy to use but what I want is add a refresh icon or update each second to get the real time data to monitor the resource usuage.

### Describe the solution you'd like

when get the data from data source, i.e. call a function, refresh the data every second.

### Alternative Solutions

None

### Additional context

None

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by Joseph-Perkins** [comment]
Thank you for the feature request and description @Bye-legumes! (The explanation of this feature seems clear from your description)

Updates to the way that data is refreshed are currently in and/or about to start development, so topics in the description here will likely be touched on by this ongoing development process

At this point we're not able to give a timeline of when the exact topic of live data refresh will be addressed, but when the issues for the sub-sections of that development manifest in the issue tracking list then they will be linked to / incorporated with this issue where relevant, which should make it easier to track any related progress

(any current development topics should become easier to track once issues on the roadmap manifest more clearly as issues in the repo)

**Comment by steve-playaio** [comment]
Would be great to get this feature in

**Comment by antonymilne** [comment]
Good news @steve-playaio - I am actively working on it right now, so this should be coming very soon!

**Comment by huong-li-nguyen** [comment]
Hey guys,

Good news! 🗞️ 

This is now available in the latest version, `vizro==0.1.15`. Take a look at our [user guide on data](https://vizro.readthedocs.io/en/stable/pages/user-guides/data/) for more details. You should now be able to reload your data while the dashboard is still running using **dynamic data**. You can find some basic examples in our docs!

**Comment by petar-qb** [comment]
Just to link a similar Issue with some examples in case it helps. -> https://github.com/mckinsey/vizro/issues/532
