### ISSUE TITLE
Langgraph dependency with Vizro AI

### ISSUE THREAD

**Issue by anonymouspotato12** [mckinsey/vizro#769]
### Which package?

vizro-ai

### Package version

0.2.3

### Description

Cant seem to run anything Vizro AI related because of the Langgraph dependency issue which always says ImportError: cannot import name 'V' from 'langgraph.store.base' or something else where the langgraph version needed doesnt have certain features in it.

### How to Reproduce

Run Vizro AI locally

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by lingyielia** [comment]
Hello @anonymouspotato12 , we just did a new release on Vizro-AI. Now this dependency issue should be resolved in the latest version: https://github.com/mckinsey/vizro/releases/tag/vizro-ai-0.3.0
