### ISSUE TITLE
Add other elements to Filter/Control sidebar

### ISSUE THREAD

**Issue by FSaal** [mckinsey/vizro#776]
### Question

Is it possible to add any component to the Filter/Parameter sidebar?
As far as I understood, only elements which are added as children of controls will be added to the sidebar.
But controls only takes either vm.Filter() or vm.Parameter().
I want to add a dropdown in the sidebar, which I want to control using dash callbacks.
I hope the code example helps to make clear what I want.

### Code/Examples

```
import dash_core_components as dcc
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro

iris = px.data.iris()

page = vm.Page(
    title="My first page",
    components=[
        vm.Graph(
            id="scatter_chart",
            figure=px.scatter(iris, title="My scatter chart", x="sepal_length", y="petal_width", color="species"),
        ),
    ],
    controls=[
       #Here I want to add any component, could also be dcc.Dropdown or any other custom element.
        vm.Dropdown(
            id="my-dropdown",
            ...
        ),
        vm.Parameter(
            targets=["scatter_chart.title"],
            selector=vm.Dropdown(
                options=["My scatter chart", "A better title!", "Another title..."],
                multi=False,
            ),
        ),
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()

```

### Which package?

vizro

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @FSaal 👋 

Yes, it's possible to extend the set of allowed types that can be added to the component's field. Here's an example below

```py
# Enables vm.Dropdown to be a Page control 
vm.Page.add_type("controls", vm.Dropdown)
```

**Comment by FSaal** [comment]
Thank you so much for the superfast reply @petar-qb!
Apparently I didn't read the https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-components/#extend-an-existing-component page thoroughly

**Comment by FSaal** [comment]
Thank you so much for the superfast reply @petar-qb!
Apparently I didn't read the https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-components/#extend-an-existing-component page thoroughly
