### ISSUE TITLE
Dynamic data with sliders stops working with added action

### ISSUE THREAD

**Issue by gtauzin** [mckinsey/vizro#799]
### Which package?

vizro

### Package version

0.1.24

### Description

I am building a dashboard using a dynamic data source. I have a control slider to choose the plotted data but I would also like to set up an action to save the slider value. 

With such an action added, the slider has no effect on the plot and the action itself no longer works.

### How to Reproduce

The following example can be ran in [PyCafe](https://py.cafe/snippet/vizro/v1#c=H4sIACJBBWcAA41UXY_TOhD9K5Z5SaRgbbni3qtKvbp8CR4RCHjYrCo3mTQWjm0cp9uw2v_OsZOU7i5ocavWY5-Zc2Y89g2vbE18zRtvO3ZQ371lqnPWB_Y5GqWZLSdNLXuGr6tPiwkvnLZBj4KOzlM_QY73IB1IdNo6dKX5yTVviDA66hfiSroweCrNXaQ0ck_-hKplkNt5MUJrapi2st4qr_pt3M3M0O3Ib22zdVaZ0G9WF_malYZhRBTbQKmIUBHNLJ-2PIHeJIToZec0PYiUIwoozyRcljw6lPwKUe_qSNj_56yykssqKGtKDroo2nlE3BrZgQY_-XpSkZanlejvQILIh068xyybMEEFTZuSf3LgIRZaYlUrURxrcGBw8NTgTNqSF5NDZVE8Q7EWl9NKHAj61kvXZqpGsH2cwoM1ag_BG5RoZ4_QPeVXsCNAvaNKUTJHmI6C1NtrVYfkWVlt_TkqjwWLVFcnISZ4q-_LeC89Eg7k5wSXkYT1WtU46yWXZQTp95QSmqSnA902MZC4f244nmJWsoyeNFUBckH_MTHc446jUwbNU7BOHvGPSR_IpZWD1APF2UOn6ZzvpHg-wPciIbJmMGmyOWuFvGDKuGHKa8pcJC6kMPfp-Vjquoz8zJ7hEZJaCfe43Vnp66mfXi9mFlsGfPEvcpQmPQFZLnaD0nV28suFH0yW84J7-jYoT13sKDwi6ab-t7kQK7H6tzRP2I60vUY36pEZoppqFiheX-kVlgLeGtOjc3RqXY0e7vFi4JKjGMw283sUm3kUlWzwJPihaTYg-FusGHvCOlt9LQ2ExAdkEQBTOvdZ0TVfN1L3VHCqVXhj5E4DFPyAFTeG1hq4uNHWqO7Tw4V4hqhw1nK0Q-DrGz5L4etnSNXa8MEi5M1C5mEVvGpRG08AXZ52gtz1FLCZbgRfr55fFBw99GUy_5qsd6T2LXiiqer4BitNLxG1J_8K90MqQ_43DBH6dDdhAXEyxuX89uq2eKjiNxJ_-qFcwo13vf8gu8czmhU-ls2SyK_lt3PU1T_P_4QTrweWpX6MdMFF1vi5LVJV0ceXV7c_ALsy7g4YBwAA):

```
from vizro import Vizro
import pandas as pd
import vizro.plotly.express as px
import vizro.models as vm
from vizro.models.types import capture

from vizro.managers import data_manager

def load_iris_data(number_of_points=10): 
    iris = px.data.iris()
    return iris.sample(number_of_points) 

data_manager["iris"] = load_iris_data 

@capture("action")
def print_name(name):
    print(name)

page = vm.Page(
    title="Update the chart on page refresh",
    components=[
        vm.Graph(id="graph", figure=px.box("iris", x="species", y="petal_width", color="species")) 
    ],
    controls=[
        vm.Parameter(
            id="slider",
            targets=["graph.data_frame.number_of_points"], 
            selector=vm.Slider(
                min=10, max=100, step=10, value=10,
                actions=[
                    vm.Action(function=print_name(), inputs=["slider.value"])
                ],
            ),
        )
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()
```

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @gtauzin and thanks for using Vizro! 😃 

In Vizro, when you configure a vm.Parameter, for example like this:
```py
vm.Parameter(
    targets=["graph.data_frame.number_of_points"],
    selector=vm.Slider(
        id="slider",
        min=10, max=100, step=10, value=10
    )
)
```

internally, the private `_parameter` Vizro action is assigned to the slider, and the model is adjusted to this:

```py
vm.Parameter(
    targets=["graph.data_frame.number_of_points"],
    selector=vm.Slider(
        id="slider",
        min=10, max=100, step=10, value=10,
        actions=[
            vm.Action(function=_parameter(targets=["graph.data_frame.number_of_points"]))
        ]
    )
)
```

This private `_parameter` action (and many other vizro actions enhacements) are going to become public, once we decide to merge -> https://github.com/mckinsey/vizro/pull/363. 

So, while waiting for fully native Vizro support for achieving this use-case, I'm sending you workaround solution that includes using the private Vizro _parameter action.

```py
from vizro import Vizro
import pandas as pd
import vizro.plotly.express as px
import vizro.models as vm
from vizro.models.types import capture
from vizro.actions._parameter_action import _parameter

from vizro.managers import data_manager


def load_iris_data(number_of_points=10):
    iris = px.data.iris()
    return iris.sample(number_of_points) 


data_manager["iris"] = load_iris_data 


@capture("action")
def print_name(name):
    print(name)


page = vm.Page(
    title="Update the chart on page refresh",
    components=[
        vm.Graph(id="graph", figure=px.box("iris", x="species", y="petal_width", color="species")) 
    ],
    controls=[
        vm.Parameter(
            targets=["graph.data_frame.number_of_points"],
            selector=vm.Slider(
                id="slider",
                min=10, max=100, step=10, value=10,
                actions=[
                    vm.Action(function=_parameter(targets=["graph.data_frame.number_of_points"])),
                    vm.Action(function=print_name(), inputs=["slider.value"])
                ],
            ),
        )
    ],
)

dashboard = vm.Dashboard(pages=[page])

Vizro().build(dashboard).run()
``` 

Also, you can aways combine vizro actions with [dash callbacks ](https://dash.plotly.com/basic-callbacks) if you need to implement something hacky.

**Comment by gtauzin** [comment]
Thank you @petar-qb! It is now very clear :)
