### ISSUE TITLE
Issue when splitting dashboard in different kedro nodes

### ISSUE THREAD

**Issue by gcavalis** [mckinsey/vizro#811]
### Which package?

vizro

### Package version

0.1.24

### Description

Getting error when creating the `vm.Page` with tables in one kedro node and then getting node from history and building the dashboard in the following kedro node. 

![Screenshot 2024-10-11 at 07 32 49](https://github.com/user-attachments/assets/d8655771-d81a-4f2e-8b22-c0f637ca1957)
![Screenshot 2024-10-11 at 07 32 14](https://github.com/user-attachments/assets/f9042b52-e7f2-4637-b3d7-865ca58c21fc)

```
/Users/giovanna_cavali/opt/anaconda3/envs/foundational/lib/python3.9/site-packages/vizro/models/_components/table.py", line 130, in build
    children=[html.Div(id=self._input_component_id)],
AttributeError: _input_component_id
```
The issue was fixed when I built everything in one kedro node.

### How to Reproduce

![Screenshot 2024-10-11 at 07 32 49](https://github.com/user-attachments/assets/d8655771-d81a-4f2e-8b22-c0f637ca1957)
![Screenshot 2024-10-11 at 07 32 14](https://github.com/user-attachments/assets/f9042b52-e7f2-4637-b3d7-865ca58c21fc)

### Output

```
/Users/giovanna_cavali/opt/anaconda3/envs/foundational/lib/python3.9/site-packages/vizro/models/_components/table.py", line 130, in build
    children=[html.Div(id=self._input_component_id)],
AttributeError: _input_component_id
```

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by antonymilne** [comment]
Thank you for raising the issue @gcavalis (and very nice cat 😀). The current fix is as follows, although in future this will probably just work out of the box and this won't be required.

Any Vizro models (i.e. `vm.Something`) that are passed between nodes must be done using a `MemoryDataset` with `copy_mode: assign`:
```
model:
  type: MemoryDataset
  copy_mode: assign
```

Note that the limit here is on **instantiated Vizro models**. Passing configuration round [as a dictionary](https://vizro.readthedocs.io/en/stable/pages/user-guides/dashboard/#__tabbed_1_2) doesn't need any special treatment.

Similarly, persisting a model to disk does not work well, but what does is saving configuration as a dictionary and then using any dictionary-compatible kedro dataset like `JSONDataset` or `PickleDataset`.

As a side note, to run the dashboard itself you can put `Vizro().build(dashboard).run()` in a node but if you’re a purist like me then it’s much nicer to do it in a hook instead. e.g. assuming you have a node with output "dashboard" that is the `vm.Dashboard` object then to run the dashboard after your pipeline has completed you could do this:
```
class ProjectHooks:
    @hook_impl
    def after_pipeline_run(self, catalog):
        Vizro().build(catalog.load("dashboard")).run()
```

You can make this conditional easily or change it to `after_node_run` etc. assuming you don’t always want to start the dashboard on every pipeline run. For example:
```
        if run_params["extra_params"].get("dashboard"):
```
would only run if you’ve done `kedro run --params dashboard=true`.
