### ISSUE TITLE
Localize Vizro: external scripts and custom localization

### ISSUE THREAD

**Issue by baltic-tea** [mckinsey/vizro#889]
### Question

I have two questions related to localization in Vizro:

1. Is it possible to use the same approach as in Plotly Dash to localize Vizro by loading an external JS script?  
   For example, loading the file [https://cdn.plot.ly/plotly-locale-de-latest.js](https://cdn.plot.ly/plotly-locale-de-latest.js). I tried adding this file directly to `assets/js` or embedding its content into `assets/js/custom.js`, but neither approach seems to work. Is this feature supported or are there specific steps required to enable it?

2. Are there any supported ways to create a custom localization for Vizro with overriding default texts?  
   If so, could you provide guidance or an example on how to implement it?

It would be helpful to know the current state of localization features in Vizro and any planned enhancements in this area

### Which package?

vizro

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by petar-qb** [comment]
Hi @baltic-tea, and thank you for the great question! ⭐

Since Vizro is built on top of Dash, many features available in Dash are also supported in Vizro. Regarding localisation for Plotly charts, it is indeed possible to achieve this in Vizro as well. The steps are outlined in this post from the Plotly community: https://community.plotly.com/t/localization-dash/66168.

The key is to include the `config={"locale": "de"}` property in the configuration for the `dcc.Graph` component. Since `vm.Graph` in Vizro is essentially a wrapper around `dcc.Graph`, this configuration can also be passed through `vm.Graph`.
However, the `"config"` property is not directly exposed from `vm.Graph`. To work around this, you’ll need to create a custom component. For detailed guidance on creating custom components in Vizro, you can refer to the [Vizro documentation](https://vizro.readthedocs.io/en/stable/pages/user-guides/custom-components/).

Once you add the German localisation content from the script (https://cdn.plot.ly/plotly-locale-de-latest.js) to your `assets/custom.js` file, the following example should display a chart with German names on the `x-axis`:

```py
import pandas as pd
import vizro.models as vm
import vizro.plotly.express as px
from vizro import Vizro
from typing import Literal


df = pd.DataFrame(
    {
        "date_time": pd.to_datetime(['2024-01-01', '2024-02-02', '2024-03-03','2024-04-04', '2024-05-05']),
        "value": [3, 5, 7, 5, 10],
    }
)


class LocaleGraph(vm.Graph):
    type: Literal["locale_graph"] = "locale_graph"

    config: dict

    def build(self):
        vizro_graph_obj = super().build()
        vizro_graph_obj["graph_1_id"].config = {"locale": "de"}
        return vizro_graph_obj


vm.Page.add_type("components", LocaleGraph)


page = vm.Page(
    title="Charts UI",
    components=[
        LocaleGraph(
            id="graph_1_id",
            figure=px.line(df, x="date_time", y="value"),
            config={"locale": "de"}
        ),
    ],
    controls=[
        vm.Filter(column="date_time"),
    ]
)

dashboard = vm.Dashboard(pages=[page])

if __name__ == "__main__":
    Vizro().build(dashboard).run()

```

**Comment by mohammadaffaneh** [comment]
@petar-qb  Thank you for your prompt and detailed response! I appreciate the insights you've shared and the effort you're putting into enhancing Vizro's capabilities.

Regarding your questions:

---

1. **Configurable steps that can be added or modified dynamically.**

   *What do you mean by this? The sort of thing like form fields appearing/disappearing depending on the values of previously input fields?*

   **Answer:**

   By "configurable steps that can be added or modified dynamically," I mean the ability to adjust the wizard's flow based on user inputs or external data during runtime. This includes:

   - **Adding or Removing Steps:** Introducing new steps or skipping existing ones based on conditions met in earlier steps.
   - **Modifying Step Content:** Dynamically changing the components or questions within a step depending on prior responses.
   - **Branching Logic:** Allowing the wizard to follow different paths (e.g., if a user selects "Yes," proceed to Step 3; if "No," skip to Step 5).

   This functionality enables the creation of more personalized and efficient user experiences, similar to conditional routing in forms. And yes this can be achieved by changing the 'style' property of a component within a callback.

2. **Seamless integration with external databases or APIs.**

   *Is this achieved just by connecting your `custom_callbacks={'on_complete': some_completion_function}` to something that does `request.post` or inserts a row into a database or similar? What else are you imagining here? e.g., maybe something that loads up a row from a database, allows the user to edit the values, and then save back into the database?*

   **Answer:**

   Yes, integrating with external databases or APIs would involve using callbacks to perform operations like `requests.post` or database transactions. Additionally, I envision:


   - **Real-Time Validation:** Validating inputs against external systems (e.g., checking if a username is already taken).
   - **CRUD Operations:** Allowing users to create, read, update, or delete records within the wizard interface.
   - **Two-Way Data Binding:** Ensuring changes in the wizard are reflected in external systems and vice versa, possibly using websockets or integrating a semantic layer similar to what Apache Superset offers.

3. **The validation logic is applied dynamically using the `validation_rules` defined in each Step instance.**

   *How would you expect this validation logic to be applied? On the server side or client-side? e.g., one good option here might be to use Pydantic to do validation.*

   **Answer:**

   I anticipate a hybrid approach for validation:

   - **Client-Side Validation:** For immediate feedback on input formats, required fields, and basic checks to enhance user experience and live validation.
   - **Server-Side Validation:** Utilizing libraries like Pydantic for more complex validation rules, data consistency checks, and security validations that require server resources or access to protected data.

   This ensures robust validation while maintaining responsiveness and security.

---

Thank you again for your efforts and quick reply. I'm excited about the direction Vizro is heading and am happy to assist further or provide feedback on early implementations.

**Comment by petar-qb** [comment]
Hey @mohammadaffaneh 👋 

I think your reply is at the wrong address, and you probably meant to reply to https://github.com/mckinsey/vizro/issues/888#issuecomment-2488318786.

**Comment by baltic-tea** [comment]
> ```python
> class LocaleGraph(vm.Graph):
>     type: Literal["locale_graph"] = "locale_graph"
> 
>     config: dict
> 
>     def build(self):
>         vizro_graph_obj = super().build()
>         vizro_graph_obj["graph_1_id"].config = {"locale": "de"}
>         return vizro_graph_obj
> ```

@petar-qb Maybe a more useful version of a custom class?

```python
class LocaleGraph(vm.Graph):
    type: Literal["locale_graph"] = "locale_graph"
    config: dict

    def build(self):
        vizro_graph_obj = super().build()
        vizro_graph_obj[self.id].config.update(self.config)
        return vizro_graph_obj
```

**Comment by petar-qb** [comment]
This definitely makes much more sense! Thanks @baltic-tea 🎉 

I'm closing this issue, but if you or anyone else has any other questions, we can easily reopen it.

**Comment by antonymilne** [comment]
P.S. if there's general demand for localization we could think about exposing `config` in `vm.Graph` to begin with so there's no need for a custom model. Or maybe even better just some global option you could set on `Dashboard` that applies the right config to the `dcc.Graph` and anything else where it might apply. Localization isn't something we've really thought about at all before, so maybe there's other places which could be localised as well as graphs 🤔
