### ISSUE TITLE
Add direct feature-by-feature comparisons with `streamlit` and `dash` to documentation

### ISSUE THREAD

**Issue by yury-fedotov** [mckinsey/vizro#89]
### What's the problem this feature will solve?

My first question when I saw `vizro` release note and docs was: "How is it different from `streamlit` and `dash`"?

I asked this question on slack, and thanks for the reply! Though I clearly see that many other users are asking for exactly the same thing. So that is probably a good sign that there should be a separate dedicated page in the docs elaborating on this particular comparison.

This would allow users to understand when to choose `vizro` over the other two mentioned framework, and in general advertise the product.

### Describe the solution you'd like

The best reference that comes to mind is [this comparison](https://neptune.ai/vs/mlflow) of `neptune` with `mlflow`.

- Probably to start, even a small table or couple of paragraphs of comparison would be enough.
- Long term, I'd love to see the feature-by-feature comparison just like on that page I reference - if you scroll down you'll be able to expand a huge table with like 50 parameters.

### Alternative Solutions

Another example is... `kedro-mlflow` plugin [docs](https://kedro-mlflow.readthedocs.io/en/stable/source/01_introduction/01_introduction.html#a-brief-comparison-between-kedro-and-mlflow) that compare `kedro` with `mlflow`.

### Additional context

Hopefully that helps, and I believe that this addition to documentation helps `vizro` grow.

### Code of Conduct

- [X] I agree to follow the  [Code of Conduct](https://github.com/mckinsey/vizro/blob/main/CODE_OF_CONDUCT.md).

**Comment by yuryfedotov-mck** [comment]
I see that [this PR](https://github.com/mckinsey/vizro/pull/90) does something close to this. And already helps a lot!

Though IMO there should also be a table literally with columns: `vizro` and `streamlit` and rows comparing the two.

**Comment by Joseph-Perkins** [comment]
thanks for highlighting @yuryfedotov-mck, and thank you for the suggestions and references!

as you spotted, the implementation of the table on the page which was already under way provides some more detailed information on that topic and helps to make those answers clearer

direct comparison tables such as described above are indeed potentially useful, however we strive for neutrality in discussions relating to third party tools, and there are a wide number of Python visualisation packages (each with a wide range of differing features), so at this point it is not feasible to provide a direct comparison with only an individual package or conversely to provide feature level comparisons across all those packages

however like you suggest, a more detailed feature level table extension may be revisited in future, when feasible

**Comment by yuryfedotov-mck** [comment]
Thanks @Joseph-Perkins !
The neutrality point totally makes sense. And my examples above probably "violate" that due to:

- `neptune` being a paid SaaS, and comparisons are common in commercial context.
- `kedro-mlflow` compares two other solutions with each other, not itself with something else.

So I agree that comparison I proposed might be challenging to post.

Feel free to close the issue if needed!

**Comment by yuryfedotov-mck** [comment]
Should we close this issue? I think [this section](https://vizro.readthedocs.io/en/stable/pages/explanation/why-vizro/#comparing-vizro-with-python-packages-and-business-intelligence-bi-tools-such-as-streamlit-tableau-and-powerbi) covers it well 🤗

I was opening an issue before this section of the docs was created.
